--
-- PostgreSQL database dump
--

\restrict ktdmBvE5tqwxbAdOW1WWfGeDnVpIcyMskNCW4nWsQUUAdPnEmIAuZSPjUVPeW4J

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: booking_passengers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.booking_passengers (
    booking_passengerid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    base_price numeric(38,2) NOT NULL,
    date_of_birth date NOT NULL,
    full_name character varying(255) NOT NULL,
    gender character varying(255) NOT NULL,
    passenger_type character varying(255) NOT NULL,
    requires_single_room boolean,
    single_room_surcharge numeric(38,2),
    booking_id integer NOT NULL
);


ALTER TABLE public.booking_passengers OWNER TO postgres;

--
-- Name: booking_passengers_booking_passengerid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.booking_passengers ALTER COLUMN booking_passengerid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_passengers_booking_passengerid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bookings (
    bookingid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    applied_coupon_codes text,
    booking_code character varying(20) NOT NULL,
    booking_date timestamp(6) without time zone NOT NULL,
    booking_status character varying(255),
    cancel_reason text,
    contact_address character varying(255) NOT NULL,
    contact_email character varying(255) NOT NULL,
    contact_full_name character varying(255) NOT NULL,
    contact_phone character varying(255) NOT NULL,
    coupon_discount numeric(38,2) NOT NULL,
    customer_note text,
    paid_by_coin numeric(38,2) NOT NULL,
    refund_amount numeric(38,2),
    subtotal_price numeric(38,2) NOT NULL,
    surcharge numeric(38,2),
    total_passengers integer,
    total_price numeric(38,2) NOT NULL,
    departure_id integer NOT NULL,
    user_id integer,
    CONSTRAINT bookings_booking_status_check CHECK (((booking_status)::text = ANY (ARRAY[('PENDING_PAYMENT'::character varying)::text, ('OVERDUE_PAYMENT'::character varying)::text, ('PENDING_CONFIRMATION'::character varying)::text, ('PAID'::character varying)::text, ('CANCELLED'::character varying)::text, ('PENDING_REVIEW'::character varying)::text, ('REVIEWED'::character varying)::text, ('PENDING_REFUND'::character varying)::text]))),
    CONSTRAINT bookings_subtotal_price_check CHECK ((subtotal_price >= (0)::numeric)),
    CONSTRAINT bookings_total_passengers_check CHECK ((total_passengers >= 1)),
    CONSTRAINT bookings_total_price_check CHECK ((total_price >= (0)::numeric))
);


ALTER TABLE public.bookings OWNER TO postgres;

--
-- Name: bookings_bookingid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bookings ALTER COLUMN bookingid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_bookingid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: branch_contacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.branch_contacts (
    contactid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    address character varying(255) NOT NULL,
    branch_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    is_head_office boolean,
    phone character varying(255) NOT NULL
);


ALTER TABLE public.branch_contacts OWNER TO postgres;

--
-- Name: branch_contacts_contactid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.branch_contacts ALTER COLUMN contactid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.branch_contacts_contactid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comment_likes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comment_likes (
    likeid integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    comment_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.comment_likes OWNER TO postgres;

--
-- Name: comment_likes_likeid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comment_likes ALTER COLUMN likeid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_likes_likeid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coupons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.coupons (
    couponid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    coupon_code character varying(50) NOT NULL,
    coupon_type character varying(255) NOT NULL,
    description text,
    discount_amount integer NOT NULL,
    end_date timestamp(6) without time zone,
    min_order_value numeric(38,2),
    start_date timestamp(6) without time zone,
    usage_count integer,
    usage_limit integer,
    departure_id integer,
    CONSTRAINT coupons_coupon_type_check CHECK (((coupon_type)::text = ANY (ARRAY[('GLOBAL'::character varying)::text, ('DEPARTURE'::character varying)::text]))),
    CONSTRAINT coupons_discount_amount_check CHECK ((discount_amount >= 1))
);


ALTER TABLE public.coupons OWNER TO postgres;

--
-- Name: coupons_couponid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.coupons ALTER COLUMN couponid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_couponid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departure_pricing; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departure_pricing (
    pricingid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    age_description character varying(255) NOT NULL,
    original_price numeric(38,2) NOT NULL,
    passenger_type character varying(255) NOT NULL,
    sale_price numeric(38,2),
    departure_id integer NOT NULL,
    CONSTRAINT departure_pricing_original_price_check CHECK ((original_price >= (0)::numeric)),
    CONSTRAINT departure_pricing_passenger_type_check CHECK (((passenger_type)::text = ANY (ARRAY[('ADULT'::character varying)::text, ('CHILD'::character varying)::text, ('INFANT'::character varying)::text, ('SINGLE_SUPPLEMENT'::character varying)::text]))),
    CONSTRAINT departure_pricing_sale_price_check CHECK ((sale_price >= (0)::numeric))
);


ALTER TABLE public.departure_pricing OWNER TO postgres;

--
-- Name: departure_pricing_pricingid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departure_pricing ALTER COLUMN pricingid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departure_pricing_pricingid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departure_transports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departure_transports (
    transportid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    arrival_time timestamp(6) without time zone,
    depart_time timestamp(6) without time zone,
    end_point character varying(255),
    start_point character varying(255),
    transport_code character varying(255),
    type character varying(255) NOT NULL,
    vehicle_name character varying(255),
    vehicle_type character varying(255) NOT NULL,
    departure_id integer NOT NULL,
    CONSTRAINT departure_transports_type_check CHECK (((type)::text = ANY (ARRAY[('OUTBOUND'::character varying)::text, ('INBOUND'::character varying)::text]))),
    CONSTRAINT departure_transports_vehicle_type_check CHECK (((vehicle_type)::text = ANY (ARRAY[('PLANE'::character varying)::text, ('BUS'::character varying)::text, ('TRAIN'::character varying)::text, ('SHIP'::character varying)::text, ('CAR'::character varying)::text])))
);


ALTER TABLE public.departure_transports OWNER TO postgres;

--
-- Name: departure_transports_transportid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departure_transports ALTER COLUMN transportid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departure_transports_transportid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorite_tours; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favorite_tours (
    favoriteid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    tour_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.favorite_tours OWNER TO postgres;

--
-- Name: favorite_tours_favoriteid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.favorite_tours ALTER COLUMN favoriteid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_tours_favoriteid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: followers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.followers (
    followerid integer NOT NULL,
    followed_at timestamp(6) without time zone NOT NULL,
    follower_user_id integer NOT NULL,
    following_id integer NOT NULL
);


ALTER TABLE public.followers OWNER TO postgres;

--
-- Name: followers_followerid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.followers ALTER COLUMN followerid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.followers_followerid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forum_posts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forum_posts (
    postid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    bookmark_count integer DEFAULT 0 NOT NULL,
    comment_count integer DEFAULT 0 NOT NULL,
    content text NOT NULL,
    is_featured boolean DEFAULT false NOT NULL,
    is_pinned boolean DEFAULT false NOT NULL,
    like_count integer DEFAULT 0 NOT NULL,
    post_type character varying(255) NOT NULL,
    published_at timestamp(6) without time zone,
    share_count integer DEFAULT 0 NOT NULL,
    status character varying(255) NOT NULL,
    summary character varying(200),
    thumbnail_url character varying(500),
    title character varying(300) NOT NULL,
    view_count integer DEFAULT 0 NOT NULL,
    category_id integer NOT NULL,
    tour_id integer,
    user_id integer NOT NULL,
    CONSTRAINT forum_posts_post_type_check CHECK (((post_type)::text = ANY (ARRAY[('BLOG'::character varying)::text, ('GUIDE'::character varying)::text, ('EXPERIENCE'::character varying)::text, ('QA'::character varying)::text, ('TIP'::character varying)::text, ('REVIEW_SHARE'::character varying)::text]))),
    CONSTRAINT forum_posts_status_check CHECK (((status)::text = ANY (ARRAY[('DRAFT'::character varying)::text, ('PUBLISHED'::character varying)::text, ('HIDDEN'::character varying)::text, ('DELETED'::character varying)::text])))
);


ALTER TABLE public.forum_posts OWNER TO postgres;

--
-- Name: forum_posts_postid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forum_posts ALTER COLUMN postid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forum_posts_postid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: itinerary_days; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.itinerary_days (
    itinerary_dayid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    day_number integer NOT NULL,
    details text NOT NULL,
    meals character varying(255) NOT NULL,
    title character varying(200) NOT NULL,
    tour_id integer NOT NULL,
    CONSTRAINT itinerary_days_day_number_check CHECK ((day_number >= 1))
);


ALTER TABLE public.itinerary_days OWNER TO postgres;

--
-- Name: itinerary_days_itinerary_dayid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.itinerary_days ALTER COLUMN itinerary_dayid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itinerary_days_itinerary_dayid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.locations (
    locationid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    airport_code character varying(10),
    airport_name character varying(255),
    description text,
    image character varying(255),
    name character varying(255) NOT NULL,
    region character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    status boolean,
    CONSTRAINT locations_region_check CHECK (((region)::text = ANY (ARRAY[('NORTH'::character varying)::text, ('CENTRAL'::character varying)::text, ('SOUTH'::character varying)::text])))
);


ALTER TABLE public.locations OWNER TO postgres;

--
-- Name: locations_locationid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.locations ALTER COLUMN locationid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_locationid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    notificationid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    message text,
    metadata json,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_id integer
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_notificationid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN notificationid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notificationid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payments (
    paymentid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    account_name character varying(255),
    account_number character varying(255),
    amount numeric(38,2) NOT NULL,
    bank_name character varying(255),
    bank_code character varying(255),
    bank_transaction_no character varying(255),
    payment_date timestamp(6) without time zone,
    payment_description character varying(500),
    payment_method character varying(255),
    status character varying(255),
    time_limit timestamp(6) without time zone,
    transaction_datetime timestamp(6) without time zone,
    transaction_id character varying(255),
    booking_id integer,
    CONSTRAINT payments_payment_method_check CHECK (((payment_method)::text = ANY (ARRAY[('VNPAY'::character varying)::text, ('PAYOS'::character varying)::text]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('SUCCESS'::character varying)::text, ('FAILED'::character varying)::text, ('REFUNDED'::character varying)::text])))
);


ALTER TABLE public.payments OWNER TO postgres;

--
-- Name: payments_paymentid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payments ALTER COLUMN paymentid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_paymentid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: policy_templates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.policy_templates (
    policy_templateid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    child_pricing_notes text,
    force_majeure_rules text,
    holiday_cancellation_rules text,
    packing_list text,
    payment_conditions text,
    registration_conditions text,
    regular_day_cancellation_rules text,
    status boolean,
    template_name character varying(255) NOT NULL,
    tour_price_excludes text,
    tour_price_includes text,
    contact_id integer
);


ALTER TABLE public.policy_templates OWNER TO postgres;

--
-- Name: policy_templates_policy_templateid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.policy_templates ALTER COLUMN policy_templateid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.policy_templates_policy_templateid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_bookmarks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.post_bookmarks (
    bookmarkid integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    folder_name character varying(100),
    note text,
    post_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.post_bookmarks OWNER TO postgres;

--
-- Name: post_bookmarks_bookmarkid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.post_bookmarks ALTER COLUMN bookmarkid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_bookmarks_bookmarkid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.post_categories (
    categoryid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    category_name character varying(100) NOT NULL,
    color character varying(50),
    description character varying(500),
    display_order integer NOT NULL,
    icon character varying(50),
    is_active boolean NOT NULL,
    post_count integer NOT NULL,
    slug character varying(100) NOT NULL
);


ALTER TABLE public.post_categories OWNER TO postgres;

--
-- Name: post_categories_categoryid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.post_categories ALTER COLUMN categoryid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_categories_categoryid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.post_comments (
    commentid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    content text NOT NULL,
    edited_at timestamp(6) without time zone,
    is_edited boolean NOT NULL,
    like_count integer NOT NULL,
    status character varying(255) NOT NULL,
    parent_comment_id integer,
    post_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT post_comments_status_check CHECK (((status)::text = ANY (ARRAY[('DRAFT'::character varying)::text, ('PUBLISHED'::character varying)::text, ('HIDDEN'::character varying)::text, ('DELETED'::character varying)::text])))
);


ALTER TABLE public.post_comments OWNER TO postgres;

--
-- Name: post_comments_commentid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.post_comments ALTER COLUMN commentid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_comments_commentid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.post_images (
    imageid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    alt_text character varying(100),
    caption character varying(200),
    display_order integer NOT NULL,
    file_size bigint NOT NULL,
    image_url character varying(500) NOT NULL,
    mime_type character varying(50),
    post_id integer NOT NULL,
    public_id character varying(255)
);


ALTER TABLE public.post_images OWNER TO postgres;

--
-- Name: post_images_imageid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.post_images ALTER COLUMN imageid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_images_imageid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_likes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.post_likes (
    likeid integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    post_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.post_likes OWNER TO postgres;

--
-- Name: post_likes_likeid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.post_likes ALTER COLUMN likeid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_likes_likeid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.post_tags (
    post_tagid integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    post_id integer NOT NULL,
    tag_id integer NOT NULL
);


ALTER TABLE public.post_tags OWNER TO postgres;

--
-- Name: post_tags_post_tagid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.post_tags ALTER COLUMN post_tagid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_tags_post_tagid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_views; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.post_views (
    viewid integer NOT NULL,
    ip_address character varying(45),
    session_id character varying(100),
    user_agent character varying(500),
    viewed_at timestamp(6) without time zone NOT NULL,
    post_id integer NOT NULL,
    user_id integer
);


ALTER TABLE public.post_views OWNER TO postgres;

--
-- Name: post_views_viewid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.post_views ALTER COLUMN viewid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_views_viewid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    revoked boolean NOT NULL,
    token character varying(255) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.refresh_tokens OWNER TO postgres;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refund_information; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refund_information (
    refundid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    account_name character varying(255) NOT NULL,
    account_number character varying(255) NOT NULL,
    bank_name character varying(255) NOT NULL,
    booking_id integer NOT NULL
);


ALTER TABLE public.refund_information OWNER TO postgres;

--
-- Name: refund_information_refundid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refund_information ALTER COLUMN refundid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refund_information_refundid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review_images (
    image_reviewid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    image text NOT NULL,
    review_id integer NOT NULL
);


ALTER TABLE public.review_images OWNER TO postgres;

--
-- Name: review_images_image_reviewid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.review_images ALTER COLUMN image_reviewid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_images_image_reviewid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews (
    reviewid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    comment text,
    is_visible boolean,
    rating integer NOT NULL,
    booking_id integer NOT NULL,
    tour_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT reviews_rating_check CHECK (((rating <= 5) AND (rating >= 1)))
);


ALTER TABLE public.reviews OWNER TO postgres;

--
-- Name: reviews_reviewid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews ALTER COLUMN reviewid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_reviewid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tags (
    tagid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    color character varying(50),
    description character varying(200),
    is_active boolean NOT NULL,
    slug character varying(50) NOT NULL,
    tag_name character varying(50) NOT NULL,
    usage_count integer NOT NULL
);


ALTER TABLE public.tags OWNER TO postgres;

--
-- Name: tags_tagid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tags ALTER COLUMN tagid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_tagid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tour_departures; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tour_departures (
    departureid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    available_slots integer NOT NULL,
    departure_date timestamp(6) without time zone NOT NULL,
    status boolean,
    tour_guide_info text NOT NULL,
    coupon_id integer,
    policy_template_id integer NOT NULL,
    tour_id integer NOT NULL,
    CONSTRAINT tour_departures_available_slots_check CHECK ((available_slots >= 1))
);


ALTER TABLE public.tour_departures OWNER TO postgres;

--
-- Name: tour_departures_departureid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tour_departures ALTER COLUMN departureid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tour_departures_departureid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tour_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tour_images (
    imageid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    image_url text NOT NULL,
    is_main_image boolean NOT NULL,
    tour_id integer NOT NULL
);


ALTER TABLE public.tour_images OWNER TO postgres;

--
-- Name: tour_images_imageid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tour_images ALTER COLUMN imageid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tour_images_imageid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tour_media; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tour_media (
    media_id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    description text,
    duration double precision,
    file_size bigint,
    is_primary boolean,
    media_url character varying(500) NOT NULL,
    thumbnail_url text,
    title character varying(200),
    tour_id integer NOT NULL
);


ALTER TABLE public.tour_media OWNER TO postgres;

--
-- Name: tour_media_media_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tour_media ALTER COLUMN media_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tour_media_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tours; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tours (
    tourid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    attractions text NOT NULL,
    duration character varying(255) NOT NULL,
    hotel character varying(255),
    ideal_time character varying(255),
    meals text,
    status boolean,
    suitable_customer character varying(255),
    tour_code character varying(50) NOT NULL,
    tour_name character varying(255) NOT NULL,
    transportation character varying(255) NOT NULL,
    trip_transportation character varying(255),
    end_location_id integer NOT NULL,
    start_location_id integer NOT NULL
);


ALTER TABLE public.tours OWNER TO postgres;

--
-- Name: tours_tourid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tours ALTER COLUMN tourid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tours_tourid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_notifications (
    id integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    read_at timestamp(6) without time zone,
    notification_id integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.user_notifications OWNER TO postgres;

--
-- Name: user_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    userid integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by character varying(255),
    is_deleted boolean,
    updated_at timestamp(6) without time zone,
    updated_by character varying(255),
    avatar character varying(255),
    coin_balance numeric(38,2),
    date_of_birth date,
    district_code character varying(10),
    district_name character varying(100),
    email character varying(255) NOT NULL,
    full_name character varying(100) NOT NULL,
    is_email_verified boolean NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(255),
    province_code character varying(10),
    province_name character varying(100),
    role character varying(255),
    status boolean,
    verification_token character varying(255),
    verification_token_expiry timestamp(6) without time zone,
    last_active_at timestamp(6) without time zone,
    CONSTRAINT users_coin_balance_check CHECK ((coin_balance >= (0)::numeric)),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY (ARRAY[('ADMIN'::character varying)::text, ('CUSTOMER'::character varying)::text, ('TOUR_OWNER'::character varying)::text])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_userid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN userid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_userid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking_passengers booking_passengers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking_passengers
    ADD CONSTRAINT booking_passengers_pkey PRIMARY KEY (booking_passengerid);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (bookingid);


--
-- Name: branch_contacts branch_contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.branch_contacts
    ADD CONSTRAINT branch_contacts_pkey PRIMARY KEY (contactid);


--
-- Name: comment_likes comment_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT comment_likes_pkey PRIMARY KEY (likeid);


--
-- Name: coupons coupons_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (couponid);


--
-- Name: departure_pricing departure_pricing_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departure_pricing
    ADD CONSTRAINT departure_pricing_pkey PRIMARY KEY (pricingid);


--
-- Name: departure_transports departure_transports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departure_transports
    ADD CONSTRAINT departure_transports_pkey PRIMARY KEY (transportid);


--
-- Name: favorite_tours favorite_tours_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_tours
    ADD CONSTRAINT favorite_tours_pkey PRIMARY KEY (favoriteid);


--
-- Name: followers followers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.followers
    ADD CONSTRAINT followers_pkey PRIMARY KEY (followerid);


--
-- Name: forum_posts forum_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum_posts
    ADD CONSTRAINT forum_posts_pkey PRIMARY KEY (postid);


--
-- Name: itinerary_days itinerary_days_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.itinerary_days
    ADD CONSTRAINT itinerary_days_pkey PRIMARY KEY (itinerary_dayid);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (locationid);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notificationid);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (paymentid);


--
-- Name: policy_templates policy_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.policy_templates
    ADD CONSTRAINT policy_templates_pkey PRIMARY KEY (policy_templateid);


--
-- Name: post_bookmarks post_bookmarks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_bookmarks
    ADD CONSTRAINT post_bookmarks_pkey PRIMARY KEY (bookmarkid);


--
-- Name: post_categories post_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_categories
    ADD CONSTRAINT post_categories_pkey PRIMARY KEY (categoryid);


--
-- Name: post_comments post_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_comments
    ADD CONSTRAINT post_comments_pkey PRIMARY KEY (commentid);


--
-- Name: post_images post_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_images
    ADD CONSTRAINT post_images_pkey PRIMARY KEY (imageid);


--
-- Name: post_likes post_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT post_likes_pkey PRIMARY KEY (likeid);


--
-- Name: post_tags post_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_tags
    ADD CONSTRAINT post_tags_pkey PRIMARY KEY (post_tagid);


--
-- Name: post_views post_views_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_views
    ADD CONSTRAINT post_views_pkey PRIMARY KEY (viewid);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: refund_information refund_information_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_information
    ADD CONSTRAINT refund_information_pkey PRIMARY KEY (refundid);


--
-- Name: review_images review_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review_images
    ADD CONSTRAINT review_images_pkey PRIMARY KEY (image_reviewid);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (reviewid);


--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (tagid);


--
-- Name: tour_departures tour_departures_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_departures
    ADD CONSTRAINT tour_departures_pkey PRIMARY KEY (departureid);


--
-- Name: tour_images tour_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_images
    ADD CONSTRAINT tour_images_pkey PRIMARY KEY (imageid);


--
-- Name: tour_media tour_media_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_media
    ADD CONSTRAINT tour_media_pkey PRIMARY KEY (media_id);


--
-- Name: tours tours_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tours
    ADD CONSTRAINT tours_pkey PRIMARY KEY (tourid);


--
-- Name: followers uk18jxibtxpmokj8ueve6h0cva9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.followers
    ADD CONSTRAINT uk18jxibtxpmokj8ueve6h0cva9 UNIQUE (following_id, follower_user_id);


--
-- Name: post_categories uk1bo89hitt308qq4dtptlwuk88; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_categories
    ADD CONSTRAINT uk1bo89hitt308qq4dtptlwuk88 UNIQUE (category_name);


--
-- Name: locations uk20t4fq3x8gptyyxslkcawey5v; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT uk20t4fq3x8gptyyxslkcawey5v UNIQUE (slug);


--
-- Name: tags uk2c6s9hekidseaj5vbgb3pgy3k; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT uk2c6s9hekidseaj5vbgb3pgy3k UNIQUE (tag_name);


--
-- Name: post_bookmarks uk3hralg8r0y2lc96pbp3km8mrj; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_bookmarks
    ADD CONSTRAINT uk3hralg8r0y2lc96pbp3km8mrj UNIQUE (post_id, user_id);


--
-- Name: reviews uk3p9j9vyr1qofbcxju65es206r; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT uk3p9j9vyr1qofbcxju65es206r UNIQUE (booking_id);


--
-- Name: post_likes uk5l2rj28vw5oj6f7ox746grokg; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT uk5l2rj28vw5oj6f7ox746grokg UNIQUE (post_id, user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: post_tags uk6ts07su5n4illwfq5yryob7wl; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_tags
    ADD CONSTRAINT uk6ts07su5n4illwfq5yryob7wl UNIQUE (post_id, tag_id);


--
-- Name: coupons ukf1u99ssbdsqass9ntq968codg; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT ukf1u99ssbdsqass9ntq968codg UNIQUE (coupon_code);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: comment_likes ukgu1pee3567af29uutdfy0fcjd; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT ukgu1pee3567af29uutdfy0fcjd UNIQUE (comment_id, user_id);


--
-- Name: post_categories ukhllaskutn95o5i8ixg5kjib41; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_categories
    ADD CONSTRAINT ukhllaskutn95o5i8ixg5kjib41 UNIQUE (slug);


--
-- Name: refund_information ukmputs1oiw132dhuie9j3qh8kc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_information
    ADD CONSTRAINT ukmputs1oiw132dhuie9j3qh8kc UNIQUE (booking_id);


--
-- Name: payments uknuscjm6x127hkb15kcb8n56wo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uknuscjm6x127hkb15kcb8n56wo UNIQUE (booking_id);


--
-- Name: bookings ukq97166k18hklq6ls46osbrftx; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT ukq97166k18hklq6ls46osbrftx UNIQUE (booking_code);


--
-- Name: locations ukqvgktk8bt8v993m1k9ld5036k; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT ukqvgktk8bt8v993m1k9ld5036k UNIQUE (name);


--
-- Name: tours ukr20eechhviuokimbwk1qqs7vn; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tours
    ADD CONSTRAINT ukr20eechhviuokimbwk1qqs7vn UNIQUE (tour_code);


--
-- Name: policy_templates ukrtjwyah8x7n679yxhrvgmy06m; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.policy_templates
    ADD CONSTRAINT ukrtjwyah8x7n679yxhrvgmy06m UNIQUE (template_name);


--
-- Name: tags uksn0d91hxu700qcw0n4pebp5vc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT uksn0d91hxu700qcw0n4pebp5vc UNIQUE (slug);


--
-- Name: user_notifications user_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT user_notifications_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (userid);


--
-- Name: idx_category_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_category_id ON public.forum_posts USING btree (category_id);


--
-- Name: idx_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_created_at ON public.forum_posts USING btree (created_at);


--
-- Name: idx_parent_comment_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_parent_comment_id ON public.post_comments USING btree (parent_comment_id);


--
-- Name: idx_post_comments_parent_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_post_comments_parent_id ON public.post_comments USING btree (parent_comment_id);


--
-- Name: idx_post_comments_post_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_post_comments_post_id ON public.post_comments USING btree (post_id);


--
-- Name: idx_post_comments_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_post_comments_user_id ON public.post_comments USING btree (user_id);


--
-- Name: idx_post_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_post_id ON public.post_comments USING btree (post_id);


--
-- Name: idx_post_views_post_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_post_views_post_id ON public.post_views USING btree (post_id);


--
-- Name: idx_post_views_viewed_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_post_views_viewed_at ON public.post_views USING btree (viewed_at);


--
-- Name: idx_posts_category_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_posts_category_id ON public.forum_posts USING btree (category_id);


--
-- Name: idx_posts_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_posts_created_at ON public.forum_posts USING btree (created_at);


--
-- Name: idx_posts_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_posts_status ON public.forum_posts USING btree (status);


--
-- Name: idx_posts_tour_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_posts_tour_id ON public.forum_posts USING btree (tour_id);


--
-- Name: idx_posts_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_posts_user_id ON public.forum_posts USING btree (user_id);


--
-- Name: idx_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_status ON public.forum_posts USING btree (status);


--
-- Name: idx_tour_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_tour_id ON public.forum_posts USING btree (tour_id);


--
-- Name: idx_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_id ON public.forum_posts USING btree (user_id);


--
-- Name: idx_viewed_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_viewed_at ON public.post_views USING btree (viewed_at);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(userid);


--
-- Name: post_comments fk21q7y8a124im4g0l4aaxn4ol1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_comments
    ADD CONSTRAINT fk21q7y8a124im4g0l4aaxn4ol1 FOREIGN KEY (parent_comment_id) REFERENCES public.post_comments(commentid);


--
-- Name: reviews fk28an517hrxtt2bsg93uefugrm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk28an517hrxtt2bsg93uefugrm FOREIGN KEY (booking_id) REFERENCES public.bookings(bookingid);


--
-- Name: review_images fk3aayo5bjciyemf3bvvt987hkr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review_images
    ADD CONSTRAINT fk3aayo5bjciyemf3bvvt987hkr FOREIGN KEY (review_id) REFERENCES public.reviews(reviewid);


--
-- Name: post_views fk4cwtrbu0dwyt3ukleb74nttnh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_views
    ADD CONSTRAINT fk4cwtrbu0dwyt3ukleb74nttnh FOREIGN KEY (post_id) REFERENCES public.forum_posts(postid);


--
-- Name: bookings fk4e49kloooqkbcqmg9cm8acpep; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fk4e49kloooqkbcqmg9cm8acpep FOREIGN KEY (departure_id) REFERENCES public.tour_departures(departureid);


--
-- Name: post_bookmarks fk67rtx0lnk37wuqqc7o297bno4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_bookmarks
    ADD CONSTRAINT fk67rtx0lnk37wuqqc7o297bno4 FOREIGN KEY (post_id) REFERENCES public.forum_posts(postid);


--
-- Name: comment_likes fk6h3lbneryl5pyb9ykaju7werx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT fk6h3lbneryl5pyb9ykaju7werx FOREIGN KEY (user_id) REFERENCES public.users(userid);


--
-- Name: comment_likes fk6q90s6gsqjadphkngyf3y0fop; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment_likes
    ADD CONSTRAINT fk6q90s6gsqjadphkngyf3y0fop FOREIGN KEY (comment_id) REFERENCES public.post_comments(commentid);


--
-- Name: favorite_tours fk8chvl1t7m3p2fa19wbyy1s89t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_tours
    ADD CONSTRAINT fk8chvl1t7m3p2fa19wbyy1s89t FOREIGN KEY (tour_id) REFERENCES public.tours(tourid);


--
-- Name: forum_posts fk8citpx8prg8lc1aqioud58yjy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum_posts
    ADD CONSTRAINT fk8citpx8prg8lc1aqioud58yjy FOREIGN KEY (category_id) REFERENCES public.post_categories(categoryid);


--
-- Name: itinerary_days fk8s769n6hgmwe2ijlw4oj2aud6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.itinerary_days
    ADD CONSTRAINT fk8s769n6hgmwe2ijlw4oj2aud6 FOREIGN KEY (tour_id) REFERENCES public.tours(tourid);


--
-- Name: post_bookmarks fk9b5c09u5arho7ei76d78bn7ww; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_bookmarks
    ADD CONSTRAINT fk9b5c09u5arho7ei76d78bn7ww FOREIGN KEY (user_id) REFERENCES public.users(userid);


--
-- Name: forum_posts fk9f512v035ct3wtwwx343yxh5u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum_posts
    ADD CONSTRAINT fk9f512v035ct3wtwwx343yxh5u FOREIGN KEY (user_id) REFERENCES public.users(userid);


--
-- Name: user_notifications fk9f86wonnl11hos1cuf5fibutl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT fk9f86wonnl11hos1cuf5fibutl FOREIGN KEY (user_id) REFERENCES public.users(userid);


--
-- Name: followers fk9wpcvi93mrta88v7h4msfuonh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.followers
    ADD CONSTRAINT fk9wpcvi93mrta88v7h4msfuonh FOREIGN KEY (following_id) REFERENCES public.users(userid);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(userid);


--
-- Name: post_images fkaetd8fdfqp16kbawa0osp6psr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_images
    ADD CONSTRAINT fkaetd8fdfqp16kbawa0osp6psr FOREIGN KEY (post_id) REFERENCES public.forum_posts(postid);


--
-- Name: tour_departures fkavyrqhlthcfnyatfgah7ac6bu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_departures
    ADD CONSTRAINT fkavyrqhlthcfnyatfgah7ac6bu FOREIGN KEY (coupon_id) REFERENCES public.coupons(couponid);


--
-- Name: tours fkbjhewvcwtyheu4hbwf4tyhnsg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tours
    ADD CONSTRAINT fkbjhewvcwtyheu4hbwf4tyhnsg FOREIGN KEY (start_location_id) REFERENCES public.locations(locationid);


--
-- Name: tour_media fkbs1o35hckomh307ubx5dujow8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_media
    ADD CONSTRAINT fkbs1o35hckomh307ubx5dujow8 FOREIGN KEY (tour_id) REFERENCES public.tours(tourid);


--
-- Name: payments fkc52o2b1jkxttngufqp3t7jr3h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkc52o2b1jkxttngufqp3t7jr3h FOREIGN KEY (booking_id) REFERENCES public.bookings(bookingid);


--
-- Name: reviews fkcgy7qjc1r99dp117y9en6lxye; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkcgy7qjc1r99dp117y9en6lxye FOREIGN KEY (user_id) REFERENCES public.users(userid);


--
-- Name: policy_templates fkcxaonqgsatfjieo1rmpjd3utt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.policy_templates
    ADD CONSTRAINT fkcxaonqgsatfjieo1rmpjd3utt FOREIGN KEY (contact_id) REFERENCES public.branch_contacts(contactid);


--
-- Name: bookings fkeyog2oic85xg7hsu2je2lx3s6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fkeyog2oic85xg7hsu2je2lx3s6 FOREIGN KEY (user_id) REFERENCES public.users(userid);


--
-- Name: booking_passengers fkg23xsssayx3p1pqc9g8cbgm8p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking_passengers
    ADD CONSTRAINT fkg23xsssayx3p1pqc9g8cbgm8p FOREIGN KEY (booking_id) REFERENCES public.bookings(bookingid);


--
-- Name: reviews fkg95fdc12cdl5o06q6la9jh0dm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkg95fdc12cdl5o06q6la9jh0dm FOREIGN KEY (tour_id) REFERENCES public.tours(tourid);


--
-- Name: favorite_tours fkgbgqqo6b34cdgdqmwrkiymrd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_tours
    ADD CONSTRAINT fkgbgqqo6b34cdgdqmwrkiymrd FOREIGN KEY (user_id) REFERENCES public.users(userid);


--
-- Name: departure_pricing fkgj2oi9u9b17v2djvmbydilw5v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departure_pricing
    ADD CONSTRAINT fkgj2oi9u9b17v2djvmbydilw5v FOREIGN KEY (departure_id) REFERENCES public.tour_departures(departureid);


--
-- Name: followers fkgl2oa2hkhtgh7s8vf7dnpm0vt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.followers
    ADD CONSTRAINT fkgl2oa2hkhtgh7s8vf7dnpm0vt FOREIGN KEY (follower_user_id) REFERENCES public.users(userid);


--
-- Name: post_views fkiiwykhlbhjwi5cxxcx9n76cd6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_views
    ADD CONSTRAINT fkiiwykhlbhjwi5cxxcx9n76cd6 FOREIGN KEY (user_id) REFERENCES public.users(userid);


--
-- Name: post_comments fkiq2j5kxwlrfoxfdi2xcim4otm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_comments
    ADD CONSTRAINT fkiq2j5kxwlrfoxfdi2xcim4otm FOREIGN KEY (post_id) REFERENCES public.forum_posts(postid);


--
-- Name: post_likes fkkgau5n0nlewg6o9lr4yibqgxj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT fkkgau5n0nlewg6o9lr4yibqgxj FOREIGN KEY (user_id) REFERENCES public.users(userid);


--
-- Name: forum_posts fkkrgf1jdudb0q7rk53eo0a9qo8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum_posts
    ADD CONSTRAINT fkkrgf1jdudb0q7rk53eo0a9qo8 FOREIGN KEY (tour_id) REFERENCES public.tours(tourid);


--
-- Name: post_tags fklb6lub8u17l5j493ev1xkxt7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_tags
    ADD CONSTRAINT fklb6lub8u17l5j493ev1xkxt7 FOREIGN KEY (post_id) REFERENCES public.forum_posts(postid);


--
-- Name: post_tags fkm6cfovkyqvu5rlm6ahdx3eavj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_tags
    ADD CONSTRAINT fkm6cfovkyqvu5rlm6ahdx3eavj FOREIGN KEY (tag_id) REFERENCES public.tags(tagid);


--
-- Name: refund_information fkoinr7cgspbs8yg9pginougcmt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refund_information
    ADD CONSTRAINT fkoinr7cgspbs8yg9pginougcmt FOREIGN KEY (booking_id) REFERENCES public.bookings(bookingid);


--
-- Name: post_likes fkokkih17is30o0es9hrwdik8io; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_likes
    ADD CONSTRAINT fkokkih17is30o0es9hrwdik8io FOREIGN KEY (post_id) REFERENCES public.forum_posts(postid);


--
-- Name: user_notifications fkovvx0ab3h8s9lrm6fppuadn7d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT fkovvx0ab3h8s9lrm6fppuadn7d FOREIGN KEY (notification_id) REFERENCES public.notifications(notificationid);


--
-- Name: tours fkpmm8bsitj11yugscb0fbndgjy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tours
    ADD CONSTRAINT fkpmm8bsitj11yugscb0fbndgjy FOREIGN KEY (end_location_id) REFERENCES public.locations(locationid);


--
-- Name: tour_departures fkppamisdafsgj745l8vnfmiy1p; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_departures
    ADD CONSTRAINT fkppamisdafsgj745l8vnfmiy1p FOREIGN KEY (tour_id) REFERENCES public.tours(tourid);


--
-- Name: tour_departures fkptl6xogxs30ataceext8m1ufb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_departures
    ADD CONSTRAINT fkptl6xogxs30ataceext8m1ufb FOREIGN KEY (policy_template_id) REFERENCES public.policy_templates(policy_templateid);


--
-- Name: departure_transports fkqha9tud20e266l4dlxlmknn1o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departure_transports
    ADD CONSTRAINT fkqha9tud20e266l4dlxlmknn1o FOREIGN KEY (departure_id) REFERENCES public.tour_departures(departureid);


--
-- Name: post_comments fksnxoecngu89u3fh4wdrgf0f2g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post_comments
    ADD CONSTRAINT fksnxoecngu89u3fh4wdrgf0f2g FOREIGN KEY (user_id) REFERENCES public.users(userid);


--
-- Name: coupons fkt9turfwgp8vm25vwii7kiinaq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT fkt9turfwgp8vm25vwii7kiinaq FOREIGN KEY (departure_id) REFERENCES public.tour_departures(departureid);


--
-- Name: tour_images fkth1m2rd6q6ltp8kii2msvfi5d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tour_images
    ADD CONSTRAINT fkth1m2rd6q6ltp8kii2msvfi5d FOREIGN KEY (tour_id) REFERENCES public.tours(tourid);


--
-- PostgreSQL database dump complete
--

\unrestrict ktdmBvE5tqwxbAdOW1WWfGeDnVpIcyMskNCW4nWsQUUAdPnEmIAuZSPjUVPeW4J

